channels:
  - conda-forge
  - defaults

dependencies:
  - pandas
  - geopandas
  - contextily
  - numpy
  - matplotlib
  - ipykernel
  - ipympl
  - scikit-learn
  - scipy
  - umap-learn
  - sympy
  - joblib
  - requests
  - jupyterlab_code_formatter
  - ruff
  - pip
  - git
  - pip:
      - git+https://github.com/morganjwilliams/pyrolite.git@develop#egg=pyrolite # latest develop release

# conda env create -n workshop-env -f environment.yml 
# python -m ipykernel install --user --name workshop-env